In [3]:
import numpy as np
import tensorflow as tf

idx2char = ['h', 'i', 'e', 'l', 'o']
#Teach hello: hihell -> ihello
#x_data = [[0, 1, 0, 2, 3, 3]]  #hihell
y_data = [[1, 0, 2, 3, 3, 4]]  #ihello

num_classes = 5
input_dim = 5 
sequence_length = 6  # |ihello| == 6
learning_rate = 0.1

x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)

y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)
print(x_one_hot.shape)
print(y_one_hot.shape)

tf.model = tf.keras.Sequential()


#input_shape = (1,6,5) => number of sequence (batch), length of sequence, size of input dim
cell = tf.keras.layers.LSTMCell(units=num_classes, input_shape=(sequence_length, input_dim))
tf.model.add(tf.keras.layers.RNN(cell=cell, return_sequences=True))


#tf.model.add(tf.keras.layers.LSTM(units=num_classes, input_shape=(sequence_length, input_dim), return_sequences=True))

tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='softmax')))

tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate),
                 metrics=['accuracy'])



(1, 6, 5)
(1, 6, 5)


In [4]:
#train
tf.model.fit(x_one_hot, y_one_hot, epochs=50)
tf.model.summary()

Epoch 1/50
1/1 [==============================] - 1s 566ms/sample - loss: 1.6223 - acc: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 5ms/sample - loss: 1.5093 - acc: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 5ms/sample - loss: 1.4356 - acc: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 5ms/sample - loss: 1.3618 - acc: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 5ms/sample - loss: 1.2478 - acc: 0.3333
Epoch 6/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.1050 - acc: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.9273 - acc: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.7400 - acc: 0.6667
Epoch 9/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.6146 - acc: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 5ms/sample - loss: 0.5170 - acc: 1.0000
Epoch 11/50
1/1 [==============================] - 0s 7ms/sampl

In [6]:
predictions = tf.model.predict(x_one_hot)
for i, prediction in enumerate(predictions):
    print(prediction)

    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", ''.join(result_str))

[[5.8096676e-04 9.9727255e-01 1.6587771e-03 5.8421620e-07 4.8704026e-04]
 [9.9724978e-01 6.7213965e-05 1.3822129e-03 1.2654328e-03 3.5427343e-05]
 [1.5275176e-03 1.0788556e-03 9.9722099e-01 1.7221659e-04 3.4893421e-07]
 [3.5386893e-04 1.6239462e-06 2.0848542e-04 9.9941063e-01 2.5346724e-05]
 [6.0254883e-04 1.1609592e-07 8.6989115e-07 9.9891925e-01 4.7725692e-04]
 [3.3362681e-04 3.2938668e-04 1.6498801e-08 7.6177146e-04 9.9857521e-01]]
	Prediction str:  ihello
