In [7]:
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

nb_classes = 3

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))  # use_bias is True, by default

# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
tf.model.add(tf.keras.layers.Activation('softmax'))

# use loss == categorical_crossentropy
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=2000)

print('--------------')

a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

print('--------------')
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

print('--------------')

c = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = tf.model.predict_classes(np.array([[1, 1, 0, 1]]))
print(c, c_onehot)

print('--------------')
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
all_onehot = tf.model.predict_classes(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
print(all, all_onehot)


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2000
1/1 [==============================] - 0s 915us/step - loss: 3.8279 - accuracy: 0.3750
Epoch 2/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.0274 - accuracy: 0.3750
Epoch 3/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.7020 - accuracy: 0.3750
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.6187 - accuracy: 0.3750
Epoch 5/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.5432 - accuracy: 0.5000
Epoch 6/2000
1/1 [============

1/1 [==============================] - 0s 784us/step - loss: 0.7559 - accuracy: 0.6250
Epoch 78/2000
1/1 [==============================] - 0s 854us/step - loss: 0.7015 - accuracy: 0.7500
Epoch 79/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.7528 - accuracy: 0.6250
Epoch 80/2000
1/1 [==============================] - 0s 871us/step - loss: 0.6983 - accuracy: 0.7500
Epoch 81/2000
1/1 [==============================] - 0s 942us/step - loss: 0.7499 - accuracy: 0.6250
Epoch 82/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6952 - accuracy: 0.7500
Epoch 83/2000
1/1 [==============================] - 0s 907us/step - loss: 0.7470 - accuracy: 0.6250
Epoch 84/2000
1/1 [==============================] - 0s 592us/step - loss: 0.6921 - accuracy: 0.7500
Epoch 85/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.7442 - accuracy: 0.6250
Epoch 86/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6892 - accuracy: 0.7500
Epoch 87/200

1/1 [==============================] - 0s 2ms/step - loss: 0.6145 - accuracy: 0.7500
Epoch 159/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6727 - accuracy: 0.6250
Epoch 160/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6130 - accuracy: 0.7500
Epoch 161/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6713 - accuracy: 0.6250
Epoch 162/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6114 - accuracy: 0.7500
Epoch 163/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6698 - accuracy: 0.6250
Epoch 164/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6099 - accuracy: 0.7500
Epoch 165/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6684 - accuracy: 0.6250
Epoch 166/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6084 - accuracy: 0.7500
Epoch 167/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6670 - accuracy: 0.6250
Epoch 168/2000


1/1 [==============================] - 0s 1ms/step - loss: 0.6216 - accuracy: 0.6250
Epoch 240/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5606 - accuracy: 0.7500
Epoch 241/2000
1/1 [==============================] - 0s 598us/step - loss: 0.6205 - accuracy: 0.6250
Epoch 242/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5594 - accuracy: 0.7500
Epoch 243/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6193 - accuracy: 0.6250
Epoch 244/2000
1/1 [==============================] - 0s 987us/step - loss: 0.5583 - accuracy: 0.7500
Epoch 245/2000
1/1 [==============================] - 0s 845us/step - loss: 0.6182 - accuracy: 0.6250
Epoch 246/2000
1/1 [==============================] - 0s 822us/step - loss: 0.5572 - accuracy: 0.7500
Epoch 247/2000
1/1 [==============================] - 0s 959us/step - loss: 0.6171 - accuracy: 0.6250
Epoch 248/2000
1/1 [==============================] - 0s 813us/step - loss: 0.5561 - accuracy: 0.7500
Epo

1/1 [==============================] - 0s 2ms/step - loss: 0.5195 - accuracy: 0.7500
Epoch 321/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5777 - accuracy: 0.6250
Epoch 322/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5186 - accuracy: 0.7500
Epoch 323/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5767 - accuracy: 0.6250
Epoch 324/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5176 - accuracy: 0.7500
Epoch 325/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5757 - accuracy: 0.6250
Epoch 326/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5167 - accuracy: 0.7500
Epoch 327/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5747 - accuracy: 0.6250
Epoch 328/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5158 - accuracy: 0.7500
Epoch 329/2000
1/1 [==============================] - 0s 844us/step - loss: 0.5737 - accuracy: 0.6250
Epoch 330/200

1/1 [==============================] - 0s 580us/step - loss: 0.5384 - accuracy: 0.7500
Epoch 402/2000
1/1 [==============================] - 0s 718us/step - loss: 0.4832 - accuracy: 0.7500
Epoch 403/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5375 - accuracy: 0.7500
Epoch 404/2000
1/1 [==============================] - 0s 788us/step - loss: 0.4824 - accuracy: 0.7500
Epoch 405/2000
1/1 [==============================] - 0s 601us/step - loss: 0.5365 - accuracy: 0.7500
Epoch 406/2000
1/1 [==============================] - 0s 688us/step - loss: 0.4816 - accuracy: 0.7500
Epoch 407/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5356 - accuracy: 0.7500
Epoch 408/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4807 - accuracy: 0.7500
Epoch 409/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5346 - accuracy: 0.7500
Epoch 410/2000
1/1 [==============================] - 0s 699us/step - loss: 0.4799 - accuracy: 0.7500
Epo

Epoch 482/2000
1/1 [==============================] - 0s 883us/step - loss: 0.4512 - accuracy: 0.7500
Epoch 483/2000
1/1 [==============================] - 0s 994us/step - loss: 0.4999 - accuracy: 0.8750
Epoch 484/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4504 - accuracy: 0.7500
Epoch 485/2000
1/1 [==============================] - 0s 610us/step - loss: 0.4990 - accuracy: 0.8750
Epoch 486/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4497 - accuracy: 0.7500
Epoch 487/2000
1/1 [==============================] - 0s 891us/step - loss: 0.4980 - accuracy: 0.8750
Epoch 488/2000
1/1 [==============================] - 0s 900us/step - loss: 0.4489 - accuracy: 0.7500
Epoch 489/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4971 - accuracy: 0.8750
Epoch 490/2000
1/1 [==============================] - 0s 910us/step - loss: 0.4481 - accuracy: 0.7500
Epoch 491/2000
1/1 [==============================] - 0s 863us/step - loss: 0.4962 - acc

1/1 [==============================] - 0s 737us/step - loss: 0.4213 - accuracy: 0.7500
Epoch 563/2000
1/1 [==============================] - 0s 787us/step - loss: 0.4631 - accuracy: 0.8750
Epoch 564/2000
1/1 [==============================] - 0s 704us/step - loss: 0.4205 - accuracy: 0.7500
Epoch 565/2000
1/1 [==============================] - 0s 893us/step - loss: 0.4622 - accuracy: 0.8750
Epoch 566/2000
1/1 [==============================] - 0s 867us/step - loss: 0.4198 - accuracy: 0.7500
Epoch 567/2000
1/1 [==============================] - 0s 922us/step - loss: 0.4613 - accuracy: 0.8750
Epoch 568/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4191 - accuracy: 0.7500
Epoch 569/2000
1/1 [==============================] - 0s 923us/step - loss: 0.4604 - accuracy: 0.8750
Epoch 570/2000
1/1 [==============================] - 0s 661us/step - loss: 0.4183 - accuracy: 0.7500
Epoch 571/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4595 - accuracy: 0.8750

1/1 [==============================] - 0s 688us/step - loss: 0.3926 - accuracy: 0.7500
Epoch 643/2000
1/1 [==============================] - 0s 728us/step - loss: 0.4268 - accuracy: 0.8750
Epoch 644/2000
1/1 [==============================] - 0s 757us/step - loss: 0.3919 - accuracy: 0.7500
Epoch 645/2000
1/1 [==============================] - 0s 760us/step - loss: 0.4259 - accuracy: 0.8750
Epoch 646/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.7500
Epoch 647/2000
1/1 [==============================] - 0s 733us/step - loss: 0.4250 - accuracy: 0.8750
Epoch 648/2000
1/1 [==============================] - 0s 776us/step - loss: 0.3904 - accuracy: 0.7500
Epoch 649/2000
1/1 [==============================] - 0s 835us/step - loss: 0.4241 - accuracy: 0.8750
Epoch 650/2000
1/1 [==============================] - 0s 862us/step - loss: 0.3897 - accuracy: 0.7500
Epoch 651/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4232 - accuracy: 0.8750

1/1 [==============================] - 0s 1ms/step - loss: 0.3645 - accuracy: 0.8750
Epoch 723/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3906 - accuracy: 0.8750
Epoch 724/2000
1/1 [==============================] - 0s 953us/step - loss: 0.3638 - accuracy: 0.8750
Epoch 725/2000
1/1 [==============================] - 0s 847us/step - loss: 0.3897 - accuracy: 0.8750
Epoch 726/2000
1/1 [==============================] - 0s 680us/step - loss: 0.3631 - accuracy: 0.8750
Epoch 727/2000
1/1 [==============================] - 0s 991us/step - loss: 0.3888 - accuracy: 0.8750
Epoch 728/2000
1/1 [==============================] - 0s 859us/step - loss: 0.3624 - accuracy: 0.8750
Epoch 729/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3879 - accuracy: 0.8750
Epoch 730/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3617 - accuracy: 0.8750
Epoch 731/2000
1/1 [==============================] - 0s 677us/step - loss: 0.3870 - accuracy: 0.8750
Epo

1/1 [==============================] - 0s 918us/step - loss: 0.3365 - accuracy: 0.8750
Epoch 803/2000
1/1 [==============================] - 0s 694us/step - loss: 0.3545 - accuracy: 0.8750
Epoch 804/2000
1/1 [==============================] - 0s 845us/step - loss: 0.3358 - accuracy: 0.8750
Epoch 805/2000
1/1 [==============================] - 0s 866us/step - loss: 0.3536 - accuracy: 0.8750
Epoch 806/2000
1/1 [==============================] - 0s 778us/step - loss: 0.3351 - accuracy: 0.8750
Epoch 807/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3527 - accuracy: 0.8750
Epoch 808/2000
1/1 [==============================] - 0s 996us/step - loss: 0.3344 - accuracy: 0.8750
Epoch 809/2000
1/1 [==============================] - 0s 687us/step - loss: 0.3518 - accuracy: 0.8750
Epoch 810/2000
1/1 [==============================] - 0s 869us/step - loss: 0.3337 - accuracy: 0.8750
Epoch 811/2000
1/1 [==============================] - 0s 923us/step - loss: 0.3509 - accuracy: 0.87

1/1 [==============================] - 0s 872us/step - loss: 0.3081 - accuracy: 0.8750
Epoch 883/2000
1/1 [==============================] - 0s 712us/step - loss: 0.3184 - accuracy: 0.8750
Epoch 884/2000
1/1 [==============================] - 0s 996us/step - loss: 0.3074 - accuracy: 0.8750
Epoch 885/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8750
Epoch 886/2000
1/1 [==============================] - 0s 683us/step - loss: 0.3067 - accuracy: 0.8750
Epoch 887/2000
1/1 [==============================] - 0s 632us/step - loss: 0.3166 - accuracy: 0.8750
Epoch 888/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3059 - accuracy: 0.8750
Epoch 889/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3157 - accuracy: 0.8750
Epoch 890/2000
1/1 [==============================] - 0s 850us/step - loss: 0.3052 - accuracy: 0.8750
Epoch 891/2000
1/1 [==============================] - 0s 700us/step - loss: 0.3148 - accuracy: 0.8750
E

Epoch 963/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2830 - accuracy: 0.8750
Epoch 964/2000
1/1 [==============================] - 0s 714us/step - loss: 0.2784 - accuracy: 1.0000
Epoch 965/2000
1/1 [==============================] - 0s 879us/step - loss: 0.2822 - accuracy: 0.8750
Epoch 966/2000
1/1 [==============================] - 0s 924us/step - loss: 0.2777 - accuracy: 1.0000
Epoch 967/2000
1/1 [==============================] - 0s 875us/step - loss: 0.2813 - accuracy: 0.8750
Epoch 968/2000
1/1 [==============================] - 0s 941us/step - loss: 0.2770 - accuracy: 1.0000
Epoch 969/2000
1/1 [==============================] - 0s 916us/step - loss: 0.2805 - accuracy: 0.8750
Epoch 970/2000
1/1 [==============================] - 0s 689us/step - loss: 0.2762 - accuracy: 1.0000
Epoch 971/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2796 - accuracy: 0.8750
Epoch 972/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2755 - acc

1/1 [==============================] - 0s 722us/step - loss: 0.2521 - accuracy: 1.0000
Epoch 1044/2000
1/1 [==============================] - 0s 791us/step - loss: 0.2512 - accuracy: 1.0000
Epoch 1045/2000
1/1 [==============================] - 0s 622us/step - loss: 0.2514 - accuracy: 1.0000
Epoch 1046/2000
1/1 [==============================] - 0s 675us/step - loss: 0.2507 - accuracy: 1.0000
Epoch 1047/2000
1/1 [==============================] - 0s 985us/step - loss: 0.2508 - accuracy: 1.0000
Epoch 1048/2000
1/1 [==============================] - 0s 681us/step - loss: 0.2501 - accuracy: 1.0000
Epoch 1049/2000
1/1 [==============================] - 0s 808us/step - loss: 0.2502 - accuracy: 1.0000
Epoch 1050/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2495 - accuracy: 1.0000
Epoch 1051/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2496 - accuracy: 1.0000
Epoch 1052/2000
1/1 [==============================] - 0s 917us/step - loss: 0.2490 - accurac

1/1 [==============================] - 0s 944us/step - loss: 0.2360 - accuracy: 1.0000
Epoch 1124/2000
1/1 [==============================] - 0s 953us/step - loss: 0.2358 - accuracy: 1.0000
Epoch 1125/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2357 - accuracy: 1.0000
Epoch 1126/2000
1/1 [==============================] - 0s 915us/step - loss: 0.2356 - accuracy: 1.0000
Epoch 1127/2000
1/1 [==============================] - 0s 877us/step - loss: 0.2355 - accuracy: 1.0000
Epoch 1128/2000
1/1 [==============================] - 0s 922us/step - loss: 0.2353 - accuracy: 1.0000
Epoch 1129/2000
1/1 [==============================] - 0s 921us/step - loss: 0.2352 - accuracy: 1.0000
Epoch 1130/2000
1/1 [==============================] - 0s 928us/step - loss: 0.2351 - accuracy: 1.0000
Epoch 1131/2000
1/1 [==============================] - 0s 911us/step - loss: 0.2350 - accuracy: 1.0000
Epoch 1132/2000
1/1 [==============================] - 0s 908us/step - loss: 0.2348 - accur

1/1 [==============================] - 0s 923us/step - loss: 0.2266 - accuracy: 1.0000
Epoch 1204/2000
1/1 [==============================] - 0s 702us/step - loss: 0.2265 - accuracy: 1.0000
Epoch 1205/2000
1/1 [==============================] - 0s 633us/step - loss: 0.2264 - accuracy: 1.0000
Epoch 1206/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2263 - accuracy: 1.0000
Epoch 1207/2000
1/1 [==============================] - 0s 935us/step - loss: 0.2262 - accuracy: 1.0000
Epoch 1208/2000
1/1 [==============================] - 0s 979us/step - loss: 0.2261 - accuracy: 1.0000
Epoch 1209/2000
1/1 [==============================] - 0s 950us/step - loss: 0.2260 - accuracy: 1.0000
Epoch 1210/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2259 - accuracy: 1.0000
Epoch 1211/2000
1/1 [==============================] - 0s 700us/step - loss: 0.2258 - accuracy: 1.0000
Epoch 1212/2000
1/1 [==============================] - 0s 669us/step - loss: 0.2256 - accurac

1/1 [==============================] - 0s 1ms/step - loss: 0.2182 - accuracy: 1.0000
Epoch 1283/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2181 - accuracy: 1.0000
Epoch 1284/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2179 - accuracy: 1.0000
Epoch 1285/2000
1/1 [==============================] - 0s 744us/step - loss: 0.2178 - accuracy: 1.0000
Epoch 1286/2000
1/1 [==============================] - 0s 689us/step - loss: 0.2177 - accuracy: 1.0000
Epoch 1287/2000
1/1 [==============================] - 0s 929us/step - loss: 0.2176 - accuracy: 1.0000
Epoch 1288/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2175 - accuracy: 1.0000
Epoch 1289/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2174 - accuracy: 1.0000
Epoch 1290/2000
1/1 [==============================] - 0s 688us/step - loss: 0.2173 - accuracy: 1.0000
Epoch 1291/2000
1/1 [==============================] - 0s 731us/step - loss: 0.2172 - accuracy: 1.0

1/1 [==============================] - 0s 897us/step - loss: 0.2102 - accuracy: 1.0000
Epoch 1363/2000
1/1 [==============================] - 0s 574us/step - loss: 0.2101 - accuracy: 1.0000
Epoch 1364/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2100 - accuracy: 1.0000
Epoch 1365/2000
1/1 [==============================] - 0s 943us/step - loss: 0.2099 - accuracy: 1.0000
Epoch 1366/2000
1/1 [==============================] - 0s 950us/step - loss: 0.2098 - accuracy: 1.0000
Epoch 1367/2000
1/1 [==============================] - 0s 902us/step - loss: 0.2097 - accuracy: 1.0000
Epoch 1368/2000
1/1 [==============================] - 0s 803us/step - loss: 0.2096 - accuracy: 1.0000
Epoch 1369/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2095 - accuracy: 1.0000
Epoch 1370/2000
1/1 [==============================] - 0s 823us/step - loss: 0.2094 - accuracy: 1.0000
Epoch 1371/2000
1/1 [==============================] - 0s 661us/step - loss: 0.2093 - accurac

1/1 [==============================] - 0s 705us/step - loss: 0.2028 - accuracy: 1.0000
Epoch 1442/2000
1/1 [==============================] - 0s 771us/step - loss: 0.2027 - accuracy: 1.0000
Epoch 1443/2000
1/1 [==============================] - 0s 722us/step - loss: 0.2026 - accuracy: 1.0000
Epoch 1444/2000
1/1 [==============================] - 0s 693us/step - loss: 0.2025 - accuracy: 1.0000
Epoch 1445/2000
1/1 [==============================] - 0s 901us/step - loss: 0.2024 - accuracy: 1.0000
Epoch 1446/2000
1/1 [==============================] - 0s 753us/step - loss: 0.2023 - accuracy: 1.0000
Epoch 1447/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2023 - accuracy: 1.0000
Epoch 1448/2000
1/1 [==============================] - 0s 666us/step - loss: 0.2022 - accuracy: 1.0000
Epoch 1449/2000
1/1 [==============================] - 0s 813us/step - loss: 0.2021 - accuracy: 1.0000
Epoch 1450/2000
1/1 [==============================] - 0s 751us/step - loss: 0.2020 - accur

1/1 [==============================] - 0s 887us/step - loss: 0.1959 - accuracy: 1.0000
Epoch 1521/2000
1/1 [==============================] - 0s 885us/step - loss: 0.1958 - accuracy: 1.0000
Epoch 1522/2000
1/1 [==============================] - 0s 809us/step - loss: 0.1957 - accuracy: 1.0000
Epoch 1523/2000
1/1 [==============================] - 0s 942us/step - loss: 0.1956 - accuracy: 1.0000
Epoch 1524/2000
1/1 [==============================] - 0s 995us/step - loss: 0.1956 - accuracy: 1.0000
Epoch 1525/2000
1/1 [==============================] - 0s 637us/step - loss: 0.1955 - accuracy: 1.0000
Epoch 1526/2000
1/1 [==============================] - 0s 782us/step - loss: 0.1954 - accuracy: 1.0000
Epoch 1527/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1953 - accuracy: 1.0000
Epoch 1528/2000
1/1 [==============================] - 0s 878us/step - loss: 0.1952 - accuracy: 1.0000
Epoch 1529/2000
1/1 [==============================] - 0s 651us/step - loss: 0.1951 - accur

1/1 [==============================] - 0s 942us/step - loss: 0.1894 - accuracy: 1.0000
Epoch 1601/2000
1/1 [==============================] - 0s 846us/step - loss: 0.1893 - accuracy: 1.0000
Epoch 1602/2000
1/1 [==============================] - 0s 917us/step - loss: 0.1892 - accuracy: 1.0000
Epoch 1603/2000
1/1 [==============================] - 0s 988us/step - loss: 0.1891 - accuracy: 1.0000
Epoch 1604/2000
1/1 [==============================] - 0s 937us/step - loss: 0.1890 - accuracy: 1.0000
Epoch 1605/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1890 - accuracy: 1.0000
Epoch 1606/2000
1/1 [==============================] - 0s 708us/step - loss: 0.1889 - accuracy: 1.0000
Epoch 1607/2000
1/1 [==============================] - 0s 743us/step - loss: 0.1888 - accuracy: 1.0000
Epoch 1608/2000
1/1 [==============================] - 0s 911us/step - loss: 0.1887 - accuracy: 1.0000
Epoch 1609/2000
1/1 [==============================] - 0s 941us/step - loss: 0.1887 - accur

Epoch 1680/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1832 - accuracy: 1.0000
Epoch 1681/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1832 - accuracy: 1.0000
Epoch 1682/2000
1/1 [==============================] - 0s 687us/step - loss: 0.1831 - accuracy: 1.0000
Epoch 1683/2000
1/1 [==============================] - 0s 991us/step - loss: 0.1830 - accuracy: 1.0000
Epoch 1684/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1829 - accuracy: 1.0000
Epoch 1685/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1829 - accuracy: 1.0000
Epoch 1686/2000
1/1 [==============================] - 0s 769us/step - loss: 0.1828 - accuracy: 1.0000
Epoch 1687/2000
1/1 [==============================] - 0s 806us/step - loss: 0.1827 - accuracy: 1.0000
Epoch 1688/2000
1/1 [==============================] - 0s 780us/step - loss: 0.1826 - accuracy: 1.0000
Epoch 1689/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1826

1/1 [==============================] - 0s 789us/step - loss: 0.1775 - accuracy: 1.0000
Epoch 1760/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1775 - accuracy: 1.0000
Epoch 1761/2000
1/1 [==============================] - 0s 635us/step - loss: 0.1774 - accuracy: 1.0000
Epoch 1762/2000
1/1 [==============================] - 0s 790us/step - loss: 0.1773 - accuracy: 1.0000
Epoch 1763/2000
1/1 [==============================] - 0s 815us/step - loss: 0.1773 - accuracy: 1.0000
Epoch 1764/2000
1/1 [==============================] - ETA: 0s - loss: 0.1772 - accuracy: 1.00 - 0s 847us/step - loss: 0.1772 - accuracy: 1.0000
Epoch 1765/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1771 - accuracy: 1.0000
Epoch 1766/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1770 - accuracy: 1.0000
Epoch 1767/2000
1/1 [==============================] - 0s 806us/step - loss: 0.1770 - accuracy: 1.0000
Epoch 1768/2000
1/1 [==============================] 

1/1 [==============================] - 0s 727us/step - loss: 0.1722 - accuracy: 1.0000
Epoch 1839/2000
1/1 [==============================] - 0s 988us/step - loss: 0.1721 - accuracy: 1.0000
Epoch 1840/2000
1/1 [==============================] - 0s 725us/step - loss: 0.1720 - accuracy: 1.0000
Epoch 1841/2000
1/1 [==============================] - 0s 683us/step - loss: 0.1720 - accuracy: 1.0000
Epoch 1842/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1719 - accuracy: 1.0000
Epoch 1843/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1718 - accuracy: 1.0000
Epoch 1844/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1718 - accuracy: 1.0000
Epoch 1845/2000
1/1 [==============================] - 0s 935us/step - loss: 0.1717 - accuracy: 1.0000
Epoch 1846/2000
1/1 [==============================] - 0s 626us/step - loss: 0.1716 - accuracy: 1.0000
Epoch 1847/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1716 - accuracy: 1

1/1 [==============================] - 0s 807us/step - loss: 0.1670 - accuracy: 1.0000
Epoch 1919/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1670 - accuracy: 1.0000
Epoch 1920/2000
1/1 [==============================] - 0s 703us/step - loss: 0.1669 - accuracy: 1.0000
Epoch 1921/2000
1/1 [==============================] - 0s 898us/step - loss: 0.1669 - accuracy: 1.0000
Epoch 1922/2000
1/1 [==============================] - 0s 735us/step - loss: 0.1668 - accuracy: 1.0000
Epoch 1923/2000
1/1 [==============================] - 0s 657us/step - loss: 0.1667 - accuracy: 1.0000
Epoch 1924/2000
1/1 [==============================] - 0s 820us/step - loss: 0.1667 - accuracy: 1.0000
Epoch 1925/2000
1/1 [==============================] - 0s 841us/step - loss: 0.1666 - accuracy: 1.0000
Epoch 1926/2000
1/1 [==============================] - 0s 979us/step - loss: 0.1665 - accuracy: 1.0000
Epoch 1927/2000
1/1 [==============================] - 0s 900us/step - loss: 0.1665 - accur

1/1 [==============================] - 0s 788us/step - loss: 0.1622 - accuracy: 1.0000
Epoch 1999/2000
1/1 [==============================] - 0s 870us/step - loss: 0.1621 - accuracy: 1.0000
Epoch 2000/2000
1/1 [==============================] - 0s 876us/step - loss: 0.1621 - accuracy: 1.0000
--------------
[[1.2529655e-02 9.8746049e-01 9.8600121e-06]] [1]
--------------
[[0.78878057 0.19160962 0.01960989]] [0]
--------------
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[[1.8346888e-08 3.8248091e-04 9.9961746e-01]] [2]
--------------
[[1.2529637e-02 9.8746049e-01 9.8600312e-06]
 [7.8878069e-01 1.9160941e-01 1.9609872e-02]
 [1.8346888e-08 3.8248091e-04 9.9961746e-01]] [1 0 2]
