In [2]:
import tensorflow as tf
import numpy as np


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    #noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

#very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)




[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [3]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=1000)

predictions = tf.model.predict(x_data)
score = tf.model.evaluate(x_data, y_data)

print('Prediction: \n', predictions)
print('Cost: ', score)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
8/8 [==============================] - 0s 14ms/sample - loss: 0.4990
Epoch 2/1000
8/8 [==============================] - 0s 506us/sample - loss: 0.4989
Epoch 3/1000
8/8 [==============================] - 0s 219us/sample - loss: 0.4989
Epoch 4/1000
8/8 [==============================] - 0s 173us/sample - loss: 0.4989
Epoch 5/1000
8/8 [==============================] - 0s 260us/sample - loss: 0.4988
Epoch 6/1000
8/8 [==============================] - 0s 327us/sample - loss: 0.4988
Epoch 7/1000
8/8 [=============================

Epoch 92/1000
8/8 [==============================] - 0s 89us/sample - loss: 0.4958
Epoch 93/1000
8/8 [==============================] - 0s 200us/sample - loss: 0.4958
Epoch 94/1000
8/8 [==============================] - 0s 173us/sample - loss: 0.4958
Epoch 95/1000
8/8 [==============================] - 0s 215us/sample - loss: 0.4957
Epoch 96/1000
8/8 [==============================] - 0s 285us/sample - loss: 0.4957
Epoch 97/1000
8/8 [==============================] - 0s 109us/sample - loss: 0.4957
Epoch 98/1000
8/8 [==============================] - 0s 105us/sample - loss: 0.4956
Epoch 99/1000
8/8 [==============================] - 0s 176us/sample - loss: 0.4956
Epoch 100/1000
8/8 [==============================] - 0s 180us/sample - loss: 0.4956
Epoch 101/1000
8/8 [==============================] - 0s 103us/sample - loss: 0.4955
Epoch 102/1000
8/8 [==============================] - 0s 191us/sample - loss: 0.4955
Epoch 103/1000
8/8 [==============================] - 0s 143us/sample - lo

Epoch 189/1000
8/8 [==============================] - 0s 133us/sample - loss: 0.4925
Epoch 190/1000
8/8 [==============================] - 0s 144us/sample - loss: 0.4925
Epoch 191/1000
8/8 [==============================] - 0s 145us/sample - loss: 0.4924
Epoch 192/1000
8/8 [==============================] - 0s 103us/sample - loss: 0.4924
Epoch 193/1000
8/8 [==============================] - 0s 118us/sample - loss: 0.4924
Epoch 194/1000
8/8 [==============================] - 0s 158us/sample - loss: 0.4923
Epoch 195/1000
8/8 [==============================] - 0s 127us/sample - loss: 0.4923
Epoch 196/1000
8/8 [==============================] - 0s 128us/sample - loss: 0.4923
Epoch 197/1000
8/8 [==============================] - 0s 166us/sample - loss: 0.4922
Epoch 198/1000
8/8 [==============================] - 0s 118us/sample - loss: 0.4922
Epoch 199/1000
8/8 [==============================] - 0s 167us/sample - loss: 0.4922
Epoch 200/1000
8/8 [==============================] - 0s 133us/sa

Epoch 286/1000
8/8 [==============================] - 0s 126us/sample - loss: 0.4892
Epoch 287/1000
8/8 [==============================] - 0s 138us/sample - loss: 0.4892
Epoch 288/1000
8/8 [==============================] - 0s 221us/sample - loss: 0.4891
Epoch 289/1000
8/8 [==============================] - 0s 215us/sample - loss: 0.4891
Epoch 290/1000
8/8 [==============================] - 0s 132us/sample - loss: 0.4891
Epoch 291/1000
8/8 [==============================] - 0s 157us/sample - loss: 0.4890
Epoch 292/1000
8/8 [==============================] - 0s 320us/sample - loss: 0.4890
Epoch 293/1000
8/8 [==============================] - 0s 147us/sample - loss: 0.4890
Epoch 294/1000
8/8 [==============================] - 0s 192us/sample - loss: 0.4889
Epoch 295/1000
8/8 [==============================] - 0s 171us/sample - loss: 0.4889
Epoch 296/1000
8/8 [==============================] - 0s 168us/sample - loss: 0.4889
Epoch 297/1000
8/8 [==============================] - 0s 197us/sa

Epoch 383/1000
8/8 [==============================] - 0s 209us/sample - loss: 0.4859
Epoch 384/1000
8/8 [==============================] - 0s 221us/sample - loss: 0.4859
Epoch 385/1000
8/8 [==============================] - 0s 154us/sample - loss: 0.4859
Epoch 386/1000
8/8 [==============================] - 0s 213us/sample - loss: 0.4858
Epoch 387/1000
8/8 [==============================] - 0s 142us/sample - loss: 0.4858
Epoch 388/1000
8/8 [==============================] - 0s 106us/sample - loss: 0.4858
Epoch 389/1000
8/8 [==============================] - 0s 119us/sample - loss: 0.4857
Epoch 390/1000
8/8 [==============================] - 0s 112us/sample - loss: 0.4857
Epoch 391/1000
8/8 [==============================] - 0s 114us/sample - loss: 0.4857
Epoch 392/1000
8/8 [==============================] - 0s 108us/sample - loss: 0.4856
Epoch 393/1000
8/8 [==============================] - 0s 111us/sample - loss: 0.4856
Epoch 394/1000
8/8 [==============================] - 0s 125us/sa

Epoch 480/1000
8/8 [==============================] - 0s 140us/sample - loss: 0.4827
Epoch 481/1000
8/8 [==============================] - 0s 114us/sample - loss: 0.4826
Epoch 482/1000
8/8 [==============================] - 0s 123us/sample - loss: 0.4826
Epoch 483/1000
8/8 [==============================] - 0s 177us/sample - loss: 0.4826
Epoch 484/1000
8/8 [==============================] - 0s 137us/sample - loss: 0.4825
Epoch 485/1000
8/8 [==============================] - 0s 201us/sample - loss: 0.4825
Epoch 486/1000
8/8 [==============================] - 0s 167us/sample - loss: 0.4825
Epoch 487/1000
8/8 [==============================] - 0s 116us/sample - loss: 0.4824
Epoch 488/1000
8/8 [==============================] - 0s 124us/sample - loss: 0.4824
Epoch 489/1000
8/8 [==============================] - 0s 186us/sample - loss: 0.4824
Epoch 490/1000
8/8 [==============================] - 0s 118us/sample - loss: 0.4823
Epoch 491/1000
8/8 [==============================] - 0s 118us/sa

Epoch 577/1000
8/8 [==============================] - 0s 168us/sample - loss: 0.4795
Epoch 578/1000
8/8 [==============================] - 0s 324us/sample - loss: 0.4794
Epoch 579/1000
8/8 [==============================] - 0s 144us/sample - loss: 0.4794
Epoch 580/1000
8/8 [==============================] - 0s 150us/sample - loss: 0.4794
Epoch 581/1000
8/8 [==============================] - 0s 122us/sample - loss: 0.4793
Epoch 582/1000
8/8 [==============================] - 0s 158us/sample - loss: 0.4793
Epoch 583/1000
8/8 [==============================] - 0s 128us/sample - loss: 0.4793
Epoch 584/1000
8/8 [==============================] - 0s 188us/sample - loss: 0.4792
Epoch 585/1000
8/8 [==============================] - 0s 127us/sample - loss: 0.4792
Epoch 586/1000
8/8 [==============================] - 0s 128us/sample - loss: 0.4792
Epoch 587/1000
8/8 [==============================] - 0s 139us/sample - loss: 0.4791
Epoch 588/1000
8/8 [==============================] - 0s 127us/sa

Epoch 674/1000
8/8 [==============================] - 0s 111us/sample - loss: 0.4762
Epoch 675/1000
8/8 [==============================] - 0s 106us/sample - loss: 0.4762
Epoch 676/1000
8/8 [==============================] - 0s 120us/sample - loss: 0.4762
Epoch 677/1000
8/8 [==============================] - 0s 114us/sample - loss: 0.4761
Epoch 678/1000
8/8 [==============================] - 0s 103us/sample - loss: 0.4761
Epoch 679/1000
8/8 [==============================] - 0s 187us/sample - loss: 0.4761
Epoch 680/1000
8/8 [==============================] - 0s 110us/sample - loss: 0.4760
Epoch 681/1000
8/8 [==============================] - 0s 110us/sample - loss: 0.4760
Epoch 682/1000
8/8 [==============================] - 0s 111us/sample - loss: 0.4760
Epoch 683/1000
8/8 [==============================] - 0s 100us/sample - loss: 0.4760
Epoch 684/1000
8/8 [==============================] - 0s 137us/sample - loss: 0.4759
Epoch 685/1000
8/8 [==============================] - 0s 115us/sa

Epoch 771/1000
8/8 [==============================] - 0s 109us/sample - loss: 0.4731
Epoch 772/1000
8/8 [==============================] - 0s 109us/sample - loss: 0.4730
Epoch 773/1000
8/8 [==============================] - 0s 158us/sample - loss: 0.4730
Epoch 774/1000
8/8 [==============================] - 0s 133us/sample - loss: 0.4730
Epoch 775/1000
8/8 [==============================] - 0s 124us/sample - loss: 0.4729
Epoch 776/1000
8/8 [==============================] - 0s 110us/sample - loss: 0.4729
Epoch 777/1000
8/8 [==============================] - 0s 130us/sample - loss: 0.4729
Epoch 778/1000
8/8 [==============================] - 0s 110us/sample - loss: 0.4728
Epoch 779/1000
8/8 [==============================] - 0s 108us/sample - loss: 0.4728
Epoch 780/1000
8/8 [==============================] - 0s 107us/sample - loss: 0.4728
Epoch 781/1000
8/8 [==============================] - 0s 114us/sample - loss: 0.4727
Epoch 782/1000
8/8 [==============================] - 0s 123us/sa

Epoch 868/1000
8/8 [==============================] - 0s 109us/sample - loss: 0.4699
Epoch 869/1000
8/8 [==============================] - 0s 107us/sample - loss: 0.4699
Epoch 870/1000
8/8 [==============================] - 0s 102us/sample - loss: 0.4698
Epoch 871/1000
8/8 [==============================] - 0s 111us/sample - loss: 0.4698
Epoch 872/1000
8/8 [==============================] - 0s 101us/sample - loss: 0.4698
Epoch 873/1000
8/8 [==============================] - 0s 102us/sample - loss: 0.4697
Epoch 874/1000
8/8 [==============================] - 0s 113us/sample - loss: 0.4697
Epoch 875/1000
8/8 [==============================] - 0s 109us/sample - loss: 0.4697
Epoch 876/1000
8/8 [==============================] - 0s 101us/sample - loss: 0.4696
Epoch 877/1000
8/8 [==============================] - 0s 97us/sample - loss: 0.4696
Epoch 878/1000
8/8 [==============================] - 0s 99us/sample - loss: 0.4696
Epoch 879/1000
8/8 [==============================] - 0s 103us/samp

Epoch 965/1000
8/8 [==============================] - 0s 121us/sample - loss: 0.4668
Epoch 966/1000
8/8 [==============================] - 0s 121us/sample - loss: 0.4667
Epoch 967/1000
8/8 [==============================] - 0s 116us/sample - loss: 0.4667
Epoch 968/1000
8/8 [==============================] - 0s 104us/sample - loss: 0.4667
Epoch 969/1000
8/8 [==============================] - 0s 118us/sample - loss: 0.4666
Epoch 970/1000
8/8 [==============================] - 0s 109us/sample - loss: 0.4666
Epoch 971/1000
8/8 [==============================] - 0s 225us/sample - loss: 0.4666
Epoch 972/1000
8/8 [==============================] - 0s 132us/sample - loss: 0.4665
Epoch 973/1000
8/8 [==============================] - 0s 151us/sample - loss: 0.4665
Epoch 974/1000
8/8 [==============================] - 0s 124us/sample - loss: 0.4665
Epoch 975/1000
8/8 [==============================] - 0s 122us/sample - loss: 0.4665
Epoch 976/1000
8/8 [==============================] - 0s 142us/sa