In [4]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data_file/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]


print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
tf.model.summary()

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)

print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))


[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
______________________

1/1 [==============================] - 0s 1ms/step - loss: 61.9698
Epoch 86/2000
1/1 [==============================] - 0s 719us/step - loss: 61.9205
Epoch 87/2000
1/1 [==============================] - 0s 807us/step - loss: 61.8713
Epoch 88/2000
1/1 [==============================] - 0s 1ms/step - loss: 61.8221
Epoch 89/2000
1/1 [==============================] - ETA: 0s - loss: 61.77 - 0s 820us/step - loss: 61.7730
Epoch 90/2000
1/1 [==============================] - 0s 997us/step - loss: 61.7238
Epoch 91/2000
1/1 [==============================] - 0s 709us/step - loss: 61.6748
Epoch 92/2000
1/1 [==============================] - 0s 652us/step - loss: 61.6257
Epoch 93/2000
1/1 [==============================] - 0s 1ms/step - loss: 61.5768
Epoch 94/2000
1/1 [==============================] - 0s 854us/step - loss: 61.5279
Epoch 95/2000
1/1 [==============================] - 0s 657us/step - loss: 61.4790
Epoch 96/2000
1/1 [==============================] - 0s 659us/step - loss: 61.4302


1/1 [==============================] - 0s 765us/step - loss: 57.3426
Epoch 184/2000
1/1 [==============================] - 0s 1ms/step - loss: 57.2974
Epoch 185/2000
1/1 [==============================] - 0s 1ms/step - loss: 57.2523
Epoch 186/2000
1/1 [==============================] - 0s 1ms/step - loss: 57.2072
Epoch 187/2000
1/1 [==============================] - 0s 1ms/step - loss: 57.1621
Epoch 188/2000
1/1 [==============================] - 0s 1ms/step - loss: 57.1171
Epoch 189/2000
1/1 [==============================] - 0s 898us/step - loss: 57.0721
Epoch 190/2000
1/1 [==============================] - 0s 2ms/step - loss: 57.0272
Epoch 191/2000
1/1 [==============================] - 0s 833us/step - loss: 56.9823
Epoch 192/2000
1/1 [==============================] - 0s 1ms/step - loss: 56.9374
Epoch 193/2000
1/1 [==============================] - 0s 1ms/step - loss: 56.8926
Epoch 194/2000
1/1 [==============================] - 0s 1ms/step - loss: 56.8478
Epoch 195/2000
1/1 [=====

1/1 [==============================] - 0s 905us/step - loss: 53.0999
Epoch 282/2000
1/1 [==============================] - 0s 608us/step - loss: 53.0585
Epoch 283/2000
1/1 [==============================] - ETA: 0s - loss: 53.01 - 0s 820us/step - loss: 53.0171
Epoch 284/2000
1/1 [==============================] - 0s 747us/step - loss: 52.9757
Epoch 285/2000
1/1 [==============================] - 0s 680us/step - loss: 52.9344
Epoch 286/2000
1/1 [==============================] - 0s 1ms/step - loss: 52.8932
Epoch 287/2000
1/1 [==============================] - 0s 821us/step - loss: 52.8519
Epoch 288/2000
1/1 [==============================] - 0s 620us/step - loss: 52.8107
Epoch 289/2000
1/1 [==============================] - 0s 929us/step - loss: 52.7695
Epoch 290/2000
1/1 [==============================] - 0s 1ms/step - loss: 52.7284
Epoch 291/2000
1/1 [==============================] - 0s 1ms/step - loss: 52.6873
Epoch 292/2000
1/1 [==============================] - 0s 636us/step - los

1/1 [==============================] - 0s 747us/step - loss: 49.2097
Epoch 380/2000
1/1 [==============================] - 0s 969us/step - loss: 49.1717
Epoch 381/2000
1/1 [==============================] - 0s 742us/step - loss: 49.1338
Epoch 382/2000
1/1 [==============================] - 0s 961us/step - loss: 49.0958
Epoch 383/2000
1/1 [==============================] - 0s 846us/step - loss: 49.0580
Epoch 384/2000
1/1 [==============================] - 0s 1ms/step - loss: 49.0201
Epoch 385/2000
1/1 [==============================] - 0s 1ms/step - loss: 48.9823
Epoch 386/2000
1/1 [==============================] - 0s 1ms/step - loss: 48.9445
Epoch 387/2000
1/1 [==============================] - 0s 806us/step - loss: 48.9067
Epoch 388/2000
1/1 [==============================] - 0s 907us/step - loss: 48.8690
Epoch 389/2000
1/1 [==============================] - 0s 768us/step - loss: 48.8313
Epoch 390/2000
1/1 [==============================] - 0s 764us/step - loss: 48.7937
Epoch 391/200

1/1 [==============================] - 0s 884us/step - loss: 45.6426
Epoch 478/2000
1/1 [==============================] - 0s 1ms/step - loss: 45.6078
Epoch 479/2000
1/1 [==============================] - 0s 993us/step - loss: 45.5730
Epoch 480/2000
1/1 [==============================] - 0s 1ms/step - loss: 45.5382
Epoch 481/2000
1/1 [==============================] - 0s 702us/step - loss: 45.5035
Epoch 482/2000
1/1 [==============================] - 0s 884us/step - loss: 45.4687
Epoch 483/2000
1/1 [==============================] - 0s 1ms/step - loss: 45.4341
Epoch 484/2000
1/1 [==============================] - 0s 1ms/step - loss: 45.3994
Epoch 485/2000
1/1 [==============================] - 0s 973us/step - loss: 45.3648
Epoch 486/2000
1/1 [==============================] - 0s 946us/step - loss: 45.3303
Epoch 487/2000
1/1 [==============================] - 0s 900us/step - loss: 45.2957
Epoch 488/2000
1/1 [==============================] - 0s 1ms/step - loss: 45.2612
Epoch 489/2000
1/

1/1 [==============================] - 0s 760us/step - loss: 42.3717
Epoch 576/2000
1/1 [==============================] - 0s 877us/step - loss: 42.3398
Epoch 577/2000
1/1 [==============================] - 0s 1ms/step - loss: 42.3079
Epoch 578/2000
1/1 [==============================] - 0s 732us/step - loss: 42.2760
Epoch 579/2000
1/1 [==============================] - 0s 655us/step - loss: 42.2442
Epoch 580/2000
1/1 [==============================] - 0s 1ms/step - loss: 42.2124
Epoch 581/2000
1/1 [==============================] - 0s 654us/step - loss: 42.1806
Epoch 582/2000
1/1 [==============================] - 0s 1ms/step - loss: 42.1488
Epoch 583/2000
1/1 [==============================] - 0s 854us/step - loss: 42.1171
Epoch 584/2000
1/1 [==============================] - 0s 968us/step - loss: 42.0853
Epoch 585/2000
1/1 [==============================] - 0s 979us/step - loss: 42.0537
Epoch 586/2000
1/1 [==============================] - 0s 931us/step - loss: 42.0220
Epoch 587/200

1/1 [==============================] - 0s 797us/step - loss: 39.3725
Epoch 674/2000
1/1 [==============================] - 0s 842us/step - loss: 39.3432
Epoch 675/2000
1/1 [==============================] - 0s 899us/step - loss: 39.3140
Epoch 676/2000
1/1 [==============================] - 0s 671us/step - loss: 39.2847
Epoch 677/2000
1/1 [==============================] - 0s 2ms/step - loss: 39.2555
Epoch 678/2000
1/1 [==============================] - 0s 876us/step - loss: 39.2263
Epoch 679/2000
1/1 [==============================] - 0s 996us/step - loss: 39.1972
Epoch 680/2000
1/1 [==============================] - 0s 1ms/step - loss: 39.1681
Epoch 681/2000
1/1 [==============================] - 0s 874us/step - loss: 39.1390
Epoch 682/2000
1/1 [==============================] - 0s 687us/step - loss: 39.1099
Epoch 683/2000
1/1 [==============================] - 0s 688us/step - loss: 39.0808
Epoch 684/2000
1/1 [==============================] - 0s 680us/step - loss: 39.0518
Epoch 685/2

1/1 [==============================] - 0s 866us/step - loss: 36.6222
Epoch 772/2000
1/1 [==============================] - 0s 769us/step - loss: 36.5954
Epoch 773/2000
1/1 [==============================] - 0s 1ms/step - loss: 36.5686
Epoch 774/2000
1/1 [==============================] - 0s 2ms/step - loss: 36.5417
Epoch 775/2000
1/1 [==============================] - 0s 1ms/step - loss: 36.5150
Epoch 776/2000
1/1 [==============================] - 0s 766us/step - loss: 36.4882
Epoch 777/2000
1/1 [==============================] - 0s 1ms/step - loss: 36.4615
Epoch 778/2000
1/1 [==============================] - 0s 1ms/step - loss: 36.4348
Epoch 779/2000
1/1 [==============================] - 0s 729us/step - loss: 36.4081
Epoch 780/2000
1/1 [==============================] - 0s 817us/step - loss: 36.3814
Epoch 781/2000
1/1 [==============================] - 0s 1ms/step - loss: 36.3548
Epoch 782/2000
1/1 [==============================] - 0s 1ms/step - loss: 36.3281
Epoch 783/2000
1/1 [=

1/1 [==============================] - 0s 1ms/step - loss: 34.1003
Epoch 870/2000
1/1 [==============================] - 0s 730us/step - loss: 34.0756
Epoch 871/2000
1/1 [==============================] - 0s 949us/step - loss: 34.0510
Epoch 872/2000
1/1 [==============================] - 0s 1ms/step - loss: 34.0265
Epoch 873/2000
1/1 [==============================] - 0s 1ms/step - loss: 34.0019
Epoch 874/2000
1/1 [==============================] - 0s 1ms/step - loss: 33.9774
Epoch 875/2000
1/1 [==============================] - 0s 780us/step - loss: 33.9528
Epoch 876/2000
1/1 [==============================] - 0s 1ms/step - loss: 33.9283
Epoch 877/2000
1/1 [==============================] - 0s 2ms/step - loss: 33.9038
Epoch 878/2000
1/1 [==============================] - 0s 1ms/step - loss: 33.8794
Epoch 879/2000
1/1 [==============================] - 0s 737us/step - loss: 33.8550
Epoch 880/2000
1/1 [==============================] - 0s 1ms/step - loss: 33.8305
Epoch 881/2000
1/1 [===

1/1 [==============================] - 0s 875us/step - loss: 31.7875
Epoch 968/2000
1/1 [==============================] - 0s 750us/step - loss: 31.7649
Epoch 969/2000
1/1 [==============================] - 0s 1ms/step - loss: 31.7424
Epoch 970/2000
1/1 [==============================] - 0s 2ms/step - loss: 31.7198
Epoch 971/2000
1/1 [==============================] - 0s 868us/step - loss: 31.6973
Epoch 972/2000
1/1 [==============================] - 0s 792us/step - loss: 31.6748
Epoch 973/2000
1/1 [==============================] - 0s 1ms/step - loss: 31.6524
Epoch 974/2000
1/1 [==============================] - 0s 2ms/step - loss: 31.6299
Epoch 975/2000
1/1 [==============================] - 0s 872us/step - loss: 31.6074
Epoch 976/2000
1/1 [==============================] - 0s 757us/step - loss: 31.5850
Epoch 977/2000
1/1 [==============================] - 0s 983us/step - loss: 31.5626
Epoch 978/2000
1/1 [==============================] - 0s 2ms/step - loss: 31.5402
Epoch 979/2000
1/

1/1 [==============================] - 0s 644us/step - loss: 29.6874
Epoch 1065/2000
1/1 [==============================] - 0s 639us/step - loss: 29.6667
Epoch 1066/2000
1/1 [==============================] - 0s 583us/step - loss: 29.6460
Epoch 1067/2000
1/1 [==============================] - 0s 1ms/step - loss: 29.6253
Epoch 1068/2000
1/1 [==============================] - 0s 888us/step - loss: 29.6046
Epoch 1069/2000
1/1 [==============================] - 0s 673us/step - loss: 29.5840
Epoch 1070/2000
1/1 [==============================] - 0s 705us/step - loss: 29.5633
Epoch 1071/2000
1/1 [==============================] - 0s 1ms/step - loss: 29.5428
Epoch 1072/2000
1/1 [==============================] - 0s 772us/step - loss: 29.5221
Epoch 1073/2000
1/1 [==============================] - 0s 815us/step - loss: 29.5016
Epoch 1074/2000
1/1 [==============================] - 0s 1ms/step - loss: 29.4810
Epoch 1075/2000
1/1 [==============================] - 0s 907us/step - loss: 29.4604
Ep

1/1 [==============================] - 0s 1ms/step - loss: 27.7598
Epoch 1162/2000
1/1 [==============================] - 0s 842us/step - loss: 27.7408
Epoch 1163/2000
1/1 [==============================] - 0s 765us/step - loss: 27.7218
Epoch 1164/2000
1/1 [==============================] - 0s 725us/step - loss: 27.7028
Epoch 1165/2000
1/1 [==============================] - 0s 1ms/step - loss: 27.6838
Epoch 1166/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.6648
Epoch 1167/2000
1/1 [==============================] - 0s 1ms/step - loss: 27.6459
Epoch 1168/2000
1/1 [==============================] - 0s 744us/step - loss: 27.6270
Epoch 1169/2000
1/1 [==============================] - 0s 1ms/step - loss: 27.6081
Epoch 1170/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.5892
Epoch 1171/2000
1/1 [==============================] - 0s 719us/step - loss: 27.5703
Epoch 1172/2000
1/1 [==============================] - 0s 1ms/step - loss: 27.5514
Epoch 1173

1/1 [==============================] - 0s 799us/step - loss: 25.9905
Epoch 1259/2000
1/1 [==============================] - 0s 747us/step - loss: 25.9730
Epoch 1260/2000
1/1 [==============================] - 0s 913us/step - loss: 25.9555
Epoch 1261/2000
1/1 [==============================] - 0s 1ms/step - loss: 25.9381
Epoch 1262/2000
1/1 [==============================] - 0s 1ms/step - loss: 25.9207
Epoch 1263/2000
1/1 [==============================] - 0s 807us/step - loss: 25.9033
Epoch 1264/2000
1/1 [==============================] - 0s 981us/step - loss: 25.8859
Epoch 1265/2000
1/1 [==============================] - 0s 1ms/step - loss: 25.8685
Epoch 1266/2000
1/1 [==============================] - 0s 681us/step - loss: 25.8512
Epoch 1267/2000
1/1 [==============================] - 0s 705us/step - loss: 25.8338
Epoch 1268/2000
1/1 [==============================] - 0s 830us/step - loss: 25.8165
Epoch 1269/2000
1/1 [==============================] - 0s 718us/step - loss: 25.7992
Ep

1/1 [==============================] - 0s 2ms/step - loss: 24.3663
Epoch 1356/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.3503
Epoch 1357/2000
1/1 [==============================] - 0s 918us/step - loss: 24.3343
Epoch 1358/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.3183
Epoch 1359/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.3023
Epoch 1360/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.2864
Epoch 1361/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.2704
Epoch 1362/2000
1/1 [==============================] - ETA: 0s - loss: 24.25 - 0s 983us/step - loss: 24.2545
Epoch 1363/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.2385
Epoch 1364/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.2226
Epoch 1365/2000
1/1 [==============================] - 0s 800us/step - loss: 24.2067
Epoch 1366/2000
1/1 [==============================] - 0s 742us/step - lo

1/1 [==============================] - 0s 945us/step - loss: 22.8902
Epoch 1452/2000
1/1 [==============================] - 0s 943us/step - loss: 22.8755
Epoch 1453/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.8608
Epoch 1454/2000
1/1 [==============================] - 0s 706us/step - loss: 22.8461
Epoch 1455/2000
1/1 [==============================] - 0s 824us/step - loss: 22.8314
Epoch 1456/2000
1/1 [==============================] - 0s 803us/step - loss: 22.8167
Epoch 1457/2000
1/1 [==============================] - 0s 1ms/step - loss: 22.8021
Epoch 1458/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.7874
Epoch 1459/2000
1/1 [==============================] - 0s 1ms/step - loss: 22.7728
Epoch 1460/2000
1/1 [==============================] - 0s 946us/step - loss: 22.7582
Epoch 1461/2000
1/1 [==============================] - 0s 949us/step - loss: 22.7435
Epoch 1462/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.7289
Epoch 

1/1 [==============================] - 0s 930us/step - loss: 21.5205
Epoch 1549/2000
1/1 [==============================] - 0s 1ms/step - loss: 21.5070
Epoch 1550/2000
1/1 [==============================] - 0s 1ms/step - loss: 21.4935
Epoch 1551/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.4800
Epoch 1552/2000
1/1 [==============================] - 0s 874us/step - loss: 21.4665
Epoch 1553/2000
1/1 [==============================] - 0s 888us/step - loss: 21.4530
Epoch 1554/2000
1/1 [==============================] - 0s 1ms/step - loss: 21.4396
Epoch 1555/2000
1/1 [==============================] - 0s 948us/step - loss: 21.4261
Epoch 1556/2000
1/1 [==============================] - 0s 1ms/step - loss: 21.4127
Epoch 1557/2000
1/1 [==============================] - 0s 984us/step - loss: 21.3993
Epoch 1558/2000
1/1 [==============================] - 0s 818us/step - loss: 21.3859
Epoch 1559/2000
1/1 [==============================] - 0s 885us/step - loss: 21.3725
Epoch 

1/1 [==============================] - 0s 1ms/step - loss: 20.2632
Epoch 1646/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.2507
Epoch 1647/2000
1/1 [==============================] - 0s 941us/step - loss: 20.2383
Epoch 1648/2000
1/1 [==============================] - 0s 1ms/step - loss: 20.2260
Epoch 1649/2000
1/1 [==============================] - 0s 1ms/step - loss: 20.2136
Epoch 1650/2000
1/1 [==============================] - 0s 1ms/step - loss: 20.2012
Epoch 1651/2000
1/1 [==============================] - 0s 1ms/step - loss: 20.1889
Epoch 1652/2000
1/1 [==============================] - 0s 995us/step - loss: 20.1765
Epoch 1653/2000
1/1 [==============================] - 0s 1ms/step - loss: 20.1642
Epoch 1654/2000
1/1 [==============================] - 0s 710us/step - loss: 20.1519
Epoch 1655/2000
1/1 [==============================] - 0s 1ms/step - loss: 20.1396
Epoch 1656/2000
1/1 [==============================] - 0s 990us/step - loss: 20.1273
Epoch 1657/2

1/1 [==============================] - 0s 934us/step - loss: 19.1089
Epoch 1743/2000
1/1 [==============================] - 0s 901us/step - loss: 19.0975
Epoch 1744/2000
1/1 [==============================] - 0s 969us/step - loss: 19.0861
Epoch 1745/2000
1/1 [==============================] - 0s 3ms/step - loss: 19.0747
Epoch 1746/2000
1/1 [==============================] - 0s 907us/step - loss: 19.0634
Epoch 1747/2000
1/1 [==============================] - 0s 1ms/step - loss: 19.0520
Epoch 1748/2000
1/1 [==============================] - 0s 835us/step - loss: 19.0407
Epoch 1749/2000
1/1 [==============================] - 0s 745us/step - loss: 19.0294
Epoch 1750/2000
1/1 [==============================] - 0s 2ms/step - loss: 19.0180
Epoch 1751/2000
1/1 [==============================] - 0s 1ms/step - loss: 19.0067
Epoch 1752/2000
1/1 [==============================] - 0s 1ms/step - loss: 18.9954
Epoch 1753/2000
1/1 [==============================] - 0s 985us/step - loss: 18.9842
Epoch 

1/1 [==============================] - 0s 1ms/step - loss: 18.0598
Epoch 1839/2000
1/1 [==============================] - 0s 1ms/step - loss: 18.0493
Epoch 1840/2000
1/1 [==============================] - 0s 1ms/step - loss: 18.0388
Epoch 1841/2000
1/1 [==============================] - 0s 614us/step - loss: 18.0284
Epoch 1842/2000
1/1 [==============================] - 0s 850us/step - loss: 18.0179
Epoch 1843/2000
1/1 [==============================] - 0s 790us/step - loss: 18.0075
Epoch 1844/2000
1/1 [==============================] - 0s 1ms/step - loss: 17.9971
Epoch 1845/2000
1/1 [==============================] - 0s 690us/step - loss: 17.9867
Epoch 1846/2000
1/1 [==============================] - 0s 814us/step - loss: 17.9763
Epoch 1847/2000
1/1 [==============================] - 0s 1ms/step - loss: 17.9659
Epoch 1848/2000
1/1 [==============================] - 0s 1ms/step - loss: 17.9555
Epoch 1849/2000
1/1 [==============================] - ETA: 0s - loss: 17.94 - 0s 1ms/step - 

1/1 [==============================] - 0s 1ms/step - loss: 17.0861
Epoch 1936/2000
1/1 [==============================] - 0s 726us/step - loss: 17.0765
Epoch 1937/2000
1/1 [==============================] - 0s 1ms/step - loss: 17.0669
Epoch 1938/2000
1/1 [==============================] - 0s 924us/step - loss: 17.0573
Epoch 1939/2000
1/1 [==============================] - 0s 808us/step - loss: 17.0477
Epoch 1940/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.0382
Epoch 1941/2000
1/1 [==============================] - 0s 1ms/step - loss: 17.0286
Epoch 1942/2000
1/1 [==============================] - 0s 1ms/step - loss: 17.0190
Epoch 1943/2000
1/1 [==============================] - 0s 770us/step - loss: 17.0095
Epoch 1944/2000
1/1 [==============================] - 0s 821us/step - loss: 16.9999
Epoch 1945/2000
1/1 [==============================] - 0s 1ms/step - loss: 16.9904
Epoch 1946/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.9809
Epoch 1947