In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data_file/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

'''
(101, 16) (101, 1)
'''

nb_classes = 7  # 0 ~ 6


y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_one_hot, epochs=1000)

# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]])
print(tf.model.predict(test_data), tf.model.predict_classes(test_data))

# Full x_data test
pred = tf.model.predict_classes(x_data)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))


(101, 16) (101, 1)
one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0

4/4 [==============================] - 0s 929us/step - loss: 0.2977 - accuracy: 0.9307
Epoch 54/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2954 - accuracy: 0.9307
Epoch 55/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2919 - accuracy: 0.9307
Epoch 56/1000
4/4 [==============================] - 0s 749us/step - loss: 0.2889 - accuracy: 0.9307
Epoch 57/1000
4/4 [==============================] - 0s 989us/step - loss: 0.2847 - accuracy: 0.9406
Epoch 58/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2806 - accuracy: 0.9406
Epoch 59/1000
4/4 [==============================] - 0s 944us/step - loss: 0.2773 - accuracy: 0.9406
Epoch 60/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2749 - accuracy: 0.9406
Epoch 61/1000
4/4 [==============================] - 0s 965us/step - loss: 0.2730 - accuracy: 0.9307
Epoch 62/1000
4/4 [==============================] - 0s 740us/step - loss: 0.2710 - accuracy: 0.9307
Epoch 63/100

4/4 [==============================] - 0s 867us/step - loss: 0.1622 - accuracy: 0.9703
Epoch 135/1000
4/4 [==============================] - 0s 821us/step - loss: 0.1619 - accuracy: 0.9802
Epoch 136/1000
4/4 [==============================] - 0s 720us/step - loss: 0.1625 - accuracy: 0.9703
Epoch 137/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1610 - accuracy: 0.9703
Epoch 138/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1585 - accuracy: 0.9703
Epoch 139/1000
4/4 [==============================] - 0s 873us/step - loss: 0.1579 - accuracy: 0.9703
Epoch 140/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1566 - accuracy: 0.9703
Epoch 141/1000
4/4 [==============================] - 0s 842us/step - loss: 0.1560 - accuracy: 0.9703
Epoch 142/1000
4/4 [==============================] - 0s 703us/step - loss: 0.1547 - accuracy: 0.9901
Epoch 143/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1554 - accuracy: 0.9802
E

Epoch 215/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1129 - accuracy: 0.9901
Epoch 216/1000
4/4 [==============================] - 0s 969us/step - loss: 0.1133 - accuracy: 0.9901
Epoch 217/1000
4/4 [==============================] - 0s 750us/step - loss: 0.1126 - accuracy: 1.0000
Epoch 218/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1120 - accuracy: 1.0000
Epoch 219/1000
4/4 [==============================] - 0s 739us/step - loss: 0.1113 - accuracy: 1.0000
Epoch 220/1000
4/4 [==============================] - 0s 791us/step - loss: 0.1120 - accuracy: 0.9901
Epoch 221/1000
4/4 [==============================] - 0s 815us/step - loss: 0.1103 - accuracy: 1.0000
Epoch 222/1000
4/4 [==============================] - 0s 805us/step - loss: 0.1096 - accuracy: 1.0000
Epoch 223/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1094 - accuracy: 1.0000
Epoch 224/1000
4/4 [==============================] - 0s 761us/step - loss: 0.1093 - acc

4/4 [==============================] - 0s 715us/step - loss: 0.0877 - accuracy: 1.0000
Epoch 296/1000
4/4 [==============================] - 0s 947us/step - loss: 0.0870 - accuracy: 1.0000
Epoch 297/1000
4/4 [==============================] - 0s 961us/step - loss: 0.0863 - accuracy: 1.0000
Epoch 298/1000
4/4 [==============================] - 0s 791us/step - loss: 0.0863 - accuracy: 1.0000
Epoch 299/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0864 - accuracy: 1.0000
Epoch 300/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0859 - accuracy: 1.0000
Epoch 301/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0856 - accuracy: 1.0000
Epoch 302/1000
4/4 [==============================] - 0s 697us/step - loss: 0.0852 - accuracy: 1.0000
Epoch 303/1000
4/4 [==============================] - 0s 934us/step - loss: 0.0853 - accuracy: 1.0000
Epoch 304/1000
4/4 [==============================] - 0s 924us/step - loss: 0.0846 - accuracy: 1.0000
E

4/4 [==============================] - 0s 764us/step - loss: 0.0713 - accuracy: 1.0000
Epoch 376/1000
4/4 [==============================] - 0s 852us/step - loss: 0.0729 - accuracy: 1.0000
Epoch 377/1000
4/4 [==============================] - 0s 927us/step - loss: 0.0714 - accuracy: 1.0000
Epoch 378/1000
4/4 [==============================] - 0s 865us/step - loss: 0.0711 - accuracy: 1.0000
Epoch 379/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0700 - accuracy: 1.0000
Epoch 380/1000
4/4 [==============================] - 0s 761us/step - loss: 0.0697 - accuracy: 1.0000
Epoch 381/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0696 - accuracy: 1.0000
Epoch 382/1000
4/4 [==============================] - 0s 858us/step - loss: 0.0697 - accuracy: 1.0000
Epoch 383/1000
4/4 [==============================] - 0s 782us/step - loss: 0.0698 - accuracy: 1.0000
Epoch 384/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0701 - accuracy: 1.0000
E

4/4 [==============================] - 0s 755us/step - loss: 0.0594 - accuracy: 1.0000
Epoch 456/1000
4/4 [==============================] - 0s 834us/step - loss: 0.0591 - accuracy: 1.0000
Epoch 457/1000
4/4 [==============================] - 0s 908us/step - loss: 0.0594 - accuracy: 1.0000
Epoch 458/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0588 - accuracy: 1.0000
Epoch 459/1000
4/4 [==============================] - 0s 987us/step - loss: 0.0596 - accuracy: 1.0000
Epoch 460/1000
4/4 [==============================] - 0s 979us/step - loss: 0.0592 - accuracy: 1.0000
Epoch 461/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0603 - accuracy: 1.0000
Epoch 462/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0589 - accuracy: 1.0000
Epoch 463/1000
4/4 [==============================] - 0s 781us/step - loss: 0.0585 - accuracy: 1.0000
Epoch 464/1000
4/4 [==============================] - 0s 787us/step - loss: 0.0583 - accuracy: 1.0000
E

4/4 [==============================] - 0s 754us/step - loss: 0.0511 - accuracy: 1.0000
Epoch 536/1000
4/4 [==============================] - 0s 882us/step - loss: 0.0510 - accuracy: 1.0000
Epoch 537/1000
4/4 [==============================] - 0s 862us/step - loss: 0.0510 - accuracy: 1.0000
Epoch 538/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0510 - accuracy: 1.0000
Epoch 539/1000
4/4 [==============================] - 0s 817us/step - loss: 0.0507 - accuracy: 1.0000
Epoch 540/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0509 - accuracy: 1.0000
Epoch 541/1000
4/4 [==============================] - 0s 721us/step - loss: 0.0508 - accuracy: 1.0000
Epoch 542/1000
4/4 [==============================] - 0s 760us/step - loss: 0.0507 - accuracy: 1.0000
Epoch 543/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0506 - accuracy: 1.0000
Epoch 544/1000
4/4 [==============================] - 0s 757us/step - loss: 0.0508 - accuracy: 1.0000
E

Epoch 616/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0450 - accuracy: 1.0000
Epoch 617/1000
4/4 [==============================] - 0s 796us/step - loss: 0.0455 - accuracy: 1.0000
Epoch 618/1000
4/4 [==============================] - 0s 762us/step - loss: 0.0460 - accuracy: 1.0000
Epoch 619/1000
4/4 [==============================] - 0s 814us/step - loss: 0.0447 - accuracy: 1.0000
Epoch 620/1000
4/4 [==============================] - 0s 791us/step - loss: 0.0445 - accuracy: 1.0000
Epoch 621/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0444 - accuracy: 1.0000
Epoch 622/1000
4/4 [==============================] - 0s 756us/step - loss: 0.0442 - accuracy: 1.0000
Epoch 623/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0445 - accuracy: 1.0000
Epoch 624/1000
4/4 [==============================] - 0s 881us/step - loss: 0.0442 - accuracy: 1.0000
Epoch 625/1000
4/4 [==============================] - 0s 780us/step - loss: 0.0441 - acc

4/4 [==============================] - 0s 1ms/step - loss: 0.0399 - accuracy: 1.0000
Epoch 697/1000
4/4 [==============================] - 0s 782us/step - loss: 0.0398 - accuracy: 1.0000
Epoch 698/1000
4/4 [==============================] - 0s 820us/step - loss: 0.0399 - accuracy: 1.0000
Epoch 699/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0398 - accuracy: 1.0000
Epoch 700/1000
4/4 [==============================] - 0s 810us/step - loss: 0.0400 - accuracy: 1.0000
Epoch 701/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0396 - accuracy: 1.0000
Epoch 702/1000
4/4 [==============================] - 0s 725us/step - loss: 0.0398 - accuracy: 1.0000
Epoch 703/1000
4/4 [==============================] - 0s 847us/step - loss: 0.0395 - accuracy: 1.0000
Epoch 704/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0397 - accuracy: 1.0000
Epoch 705/1000
4/4 [==============================] - 0s 725us/step - loss: 0.0396 - accuracy: 1.0000
Epo

Epoch 777/1000
4/4 [==============================] - 0s 761us/step - loss: 0.0360 - accuracy: 1.0000
Epoch 778/1000
4/4 [==============================] - 0s 831us/step - loss: 0.0361 - accuracy: 1.0000
Epoch 779/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0359 - accuracy: 1.0000
Epoch 780/1000
4/4 [==============================] - 0s 932us/step - loss: 0.0359 - accuracy: 1.0000
Epoch 781/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0359 - accuracy: 1.0000
Epoch 782/1000
4/4 [==============================] - 0s 795us/step - loss: 0.0360 - accuracy: 1.0000
Epoch 783/1000
4/4 [==============================] - 0s 915us/step - loss: 0.0363 - accuracy: 1.0000
Epoch 784/1000
4/4 [==============================] - 0s 812us/step - loss: 0.0360 - accuracy: 1.0000
Epoch 785/1000
4/4 [==============================] - 0s 798us/step - loss: 0.0361 - accuracy: 1.0000
Epoch 786/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0360 - acc

4/4 [==============================] - 0s 835us/step - loss: 0.0330 - accuracy: 1.0000
Epoch 858/1000
4/4 [==============================] - 0s 931us/step - loss: 0.0334 - accuracy: 1.0000
Epoch 859/1000
4/4 [==============================] - 0s 737us/step - loss: 0.0332 - accuracy: 1.0000
Epoch 860/1000
4/4 [==============================] - 0s 823us/step - loss: 0.0330 - accuracy: 1.0000
Epoch 861/1000
4/4 [==============================] - 0s 963us/step - loss: 0.0331 - accuracy: 1.0000
Epoch 862/1000
4/4 [==============================] - 0s 874us/step - loss: 0.0335 - accuracy: 1.0000
Epoch 863/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0332 - accuracy: 1.0000
Epoch 864/1000
4/4 [==============================] - 0s 869us/step - loss: 0.0330 - accuracy: 1.0000
Epoch 865/1000
4/4 [==============================] - 0s 927us/step - loss: 0.0329 - accuracy: 1.0000
Epoch 866/1000
4/4 [==============================] - 0s 855us/step - loss: 0.0332 - accuracy: 1.00

4/4 [==============================] - 0s 964us/step - loss: 0.0303 - accuracy: 1.0000
Epoch 938/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0304 - accuracy: 1.0000
Epoch 939/1000
4/4 [==============================] - 0s 773us/step - loss: 0.0303 - accuracy: 1.0000
Epoch 940/1000
4/4 [==============================] - 0s 807us/step - loss: 0.0302 - accuracy: 1.0000
Epoch 941/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0301 - accuracy: 1.0000
Epoch 942/1000
4/4 [==============================] - 0s 935us/step - loss: 0.0302 - accuracy: 1.0000
Epoch 943/1000
4/4 [==============================] - 0s 862us/step - loss: 0.0301 - accuracy: 1.0000
Epoch 944/1000
4/4 [==============================] - 0s 964us/step - loss: 0.0300 - accuracy: 1.0000
Epoch 945/1000
4/4 [==============================] - 0s 768us/step - loss: 0.0300 - accuracy: 1.0000
Epoch 946/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0300 - accuracy: 1.0000
E